skip_commits:
  files:
    - README.md

version: 1.0.{build}

environment:
  PSGalleryNugetApiKey:
    secure: IpwbqCY/2gU1iKYzF6bPJtILUY789f9fpgt+zP0LRrOK5Y3JXajA5yk/XaRkVjuy
  GithubAuthToken:
    secure: UwJX2Xu80Ciz5sgYuYD5W6smId6FntJdCXE319JAXz4M67cyyUClkMwGBdAt0hVo

install:
- ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose

build_script:
  - cd build
  - ps: ./build.ps1
  
artifacts:
  - path: src
    name: Cake.Build.Bootstrap
    type: zip
    
deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    artifact: /.*\.ps1.*/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
      
after_deploy:
  - ps: Publish-Script -Path ($env:APPVEYOR_BUILD_FOLDER + '/src/Cake.Build.Bootstrap.ps1') -NuGetApiKey $env:PSGalleryNugetApiKey -Verbose -Force
    on:
      branch: master
      appveyor_repo_tag: true