skip_commits:
  files:
    - README.md

image: WMF 5

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

environment:
  PSGalleryNugetApiKey:
    secure: IpwbqCY/2gU1iKYzF6bPJtILUY789f9fpgt+zP0LRrOK5Y3JXajA5yk/XaRkVjuy
  GithubAuthToken:
    secure: PkFAZB6f1lwOR9i3Mn9mR+kQBszikFVxmrhtOGK7p/xKlVF8o/htJc9LSQDSi3bN

install:
- ps: Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose

build_script:
  - cd build
  - ps: ./build.ps1
  
artifacts:
  - path: src
    name: Cake.Build.Bootstrap
    type: zip
    
deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
      
after_deploy:
  - ps: Publish-Script -Path ($env:APPVEYOR_BUILD_FOLDER + '/src/Cake.Build.Bootstrap.ps1') -NuGetApiKey $env:PSGalleryNugetApiKey -Verbose -Force
    on:
      branch: master
      appveyor_repo_tag: true