skip_commits:
  files:
    - README.md

image: Visual Studio 2017

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
        $env:packageVersion = "$env:APPVEYOR_REPO_TAG_NAME" 
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
        $env:packageVersion = "0.0.1-dev"
      }

environment:
  NugetApiKey:
    secure: DIE2y66RzXWvp2Q0wIOLlBTjxILBGeHyyg3pjwWjdVrggzuj9BuMWCdfHFmt9nt2
  ChocolateyApiKey:
    secure: vt+Kpb9Ro1gprFNYT4zHComLafc1Ua+2OGhscwsZ2WmgWcIQh/Z1Ui+eoCTYa74a
  GithubAuthToken:
    secure: PkFAZB6f1lwOR9i3Mn9mR+kQBszikFVxmrhtOGK7p/xKlVF8o/htJc9LSQDSi3bN

configuration: Release

build_script:
  - cd build
  - ps: ./build.ps1 -ScriptArgs '-packageVersion="$($env:packageVersion)"'
  
artifacts:
  - path: build\*.nupkg
    name: Cake.CD
    
deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: NuGet
    api_key: $(NugetApiKey)
    artifact: /build/Cake.CD.\d.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: NuGet
    server: https://chocolatey.org/api/v2/
    api_key: $(ChocolateyApiKey)
    artifact: /build/Cake.CD.portable.\d.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true