version: 1.0.{build}

build_script:
  - cd build
  - ps: ./build.ps1
  
artifacts:
  - path: src/Cake.Build.Bootstrap.ps1
    name: Cake.Build.Bootstrap.ps1
    type: file
    
deploy:
  - provider: GitHub
    artifact: /.*\.ps1.*/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true